# QUANSKILL AI ENGINEER FOUNDATION | MINI-PROJECT 1

* **Họ và tên:** Nguyễn Hữu Anh Khoa  
* **Lớp:** K9 - AI Engineer Foundation
* **Tên dự án:** Phân tích hành vi và Dự đoán khách hàng rời bỏ dịch vụ (Telco Customer Churn Analysis & Prediction)

### 🔹 Thiết lập thư viện và Tải dữ liệu
* Thiết lập môi trường (sử dụng uv vì đây là trình quản lý nhanh và tốt nhất của python ở thời điểm hiện tại), khai báo và cấu hình các thư viện bổ trợ (NumPy, Pandas, Matplotlib)
* Tải tập dữ liệu thô Telco Customer Churn từ nguồn cấp vào hệ thống.

### 🔹 MODULE 1: NUMPY
* Thực thi 10 bài toán thao tác mảng, tính toán thống kê, vectorization nâng cao (PCA, SVD, Euclidean Distance, Cosine Similarity).

### 🔹 MODULE 2: MATHEMATICS FOR AI 
* Triển khai 10 bài toán nền tảng tối ưu hóa đại số, xác suất Bayes, đạo hàm hàm mất mát và tự cài đặt thuật toán Gradient Descent

### 🔹 MODULE 3: PANDAS 
* Thực hiện 10 bước làm sạch dữ liệu, xử lý giá trị khuyết thiếu, kỹ nghệ đặc trưng và trực quan hóa insights bằng biểu đồ đồ họa.

### Thiết lập thư viện

In [62]:
!uv pip install matplotlib # Cài đặt matplotlib để vẽ đồ thị
!uv pip install numpy # Cài đặt numpy để xử lý dữ liệu
!uv pip install pandas # Cài đặt pandas để xử lý dữ liệu dạng bảng

Using Python 3.13.13 environment at: /home/khoa/Workspaces/Quanskill-MiniProjcets/Telco-Customers-Churn/.venv
Checked 1 package in 2ms
Using Python 3.13.13 environment at: /home/khoa/Workspaces/Quanskill-MiniProjcets/Telco-Customers-Churn/.venv
Checked 1 package in 1ms
Using Python 3.13.13 environment at: /home/khoa/Workspaces/Quanskill-MiniProjcets/Telco-Customers-Churn/.venv
Checked 1 package in 1ms


### Khai báo các thư viện sử dụng

In [63]:
import numpy as np
import pandas as pd

### Load dữ liệu

In [64]:
df = pd.read_csv('../data/raw/Telco Customer Churn.csv')
# Kiểm tra dữ liệu đã được load chưa
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes


### MODULE 1: NUMPY

Q1.Load the dataset into a NumPy array using numerical features only (tenure, MonthlyCharges,TotalCharges). Check the shape and dtype of the array.

In [65]:
array = np.array([df['tenure'], df['MonthlyCharges'], df['TotalCharges']]).T
print(f"Array:\n{array}")
print(f"Shape of the array: {array.shape}")
print(f"Dtype of the array: {array.dtype}")

Array:
[[1 29.85 '29.85']
 [34 56.95 '1889.5']
 [2 53.85 '108.15']
 ...
 [11 29.6 '346.45']
 [4 74.4 '306.6']
 [66 105.65 '6844.5']]
Shape of the array: (7043, 3)
Dtype of the array: object


Q2.Compute the Mean, Median, and Standard Deviation for the columns tenure, MonthlyCharges, and TotalCharges using NumPy functions.

In [ ]:
# Lấy ra từng cột trong array để xử lý
tenure_column = array[:, 0]
monthly_charges_column = array[:, 1]
total_charges_column = array[:, 2]


print(f"Tenure column:\n{tenure_column}")
print(f"Monthly Charges column:\n{monthly_charges_column}")
print(f"Total Charges column:\n{total_charges_column}")

# Thấy rằng cột TotalCharges có kiểu dữ liệu là object
# ần chuyển đổi nó sang kiểu số để có thể tính toán được
total_charges_column = pd.to_numeric(total_charges_column, errors='coerce')
print(f"Total Charges column after conversion:\n{total_charges_column}")

mean_tenure = np.mean(tenure_column)
mean_monthly_charges = np.mean(monthly_charges_column)
mean_total_charges = np.nanmean(total_charges_column)

print(f"Mean Tenure: {mean_tenure}")
print(f"Mean Monthly Charges: {mean_monthly_charges}")
print(f"Mean Total Charges: {mean_total_charges}")

median_tenure = np.median(tenure_column)
median_monthly_charges = np.median(monthly_charges_column)
median_total_charges = np.nanmedian(total_charges_column)

print(f"Median Tenure: {median_tenure}")
print(f"Median Monthly Charges: {median_monthly_charges}")
print(f"Median Total Charges: {median_total_charges}")

standard_deviation_tenure = np.std(tenure_column)
standard_deviation_monthly_charges = np.std(monthly_charges_column)
standard_deviation_total_charges = np.nanstd(total_charges_column)

print(f"Standard Deviation Tenure: {standard_deviation_tenure}")
print(f"Standard Deviation Monthly Charges: \
      {standard_deviation_monthly_charges}")
print(f"Standard Deviation Total Charges: {standard_deviation_total_charges}")

Tenure column:
[1 34 2 ... 11 4 66]
Monthly Charges column:
[29.85 56.95 53.85 ... 29.6 74.4 105.65]
Total Charges column:
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Total Charges column after conversion:
[  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Mean Tenure: 32.37114865824223
Mean Monthly Charges: 64.76169246059922
Mean Total Charges: 2283.3004408418656
Median Tenure: 29.0
Median Monthly Charges: 70.35
Median Total Charges: 1397.475
Standard Deviation Tenure: 24.55773742286321
Standard Deviation Monthly Charges: 30.08791085493703
Standard Deviation Total Charges: 2266.610180714535


Q3.Apply Min-Max normalization to scale all numerical features to the range [0,1] using vectorized operations.

In [ ]:
# Tìm min là max của từng feature
min_tenure = np.min(tenure_column)
max_tenure = np.max(tenure_column)
min_monthly_charges = np.min(monthly_charges_column)
max_monthly_charges = np.max(monthly_charges_column)
# Do trong cột total charges có giá trị bị thiếu (NaN) sau khi chuyển đổi, nên cần bỏ qua các giá trị NaN khi tính min và max
min_total_charges = np.nanmin(total_charges_column)
max_total_charges = np.nanmax(total_charges_column)

print(f"Min Tenure: {min_tenure}, Max Tenure: {max_tenure}")
print(f"Min Monthly Charges: {min_monthly_charges}, Max Monthly Charges: {max_monthly_charges}")
print(f"Min Total Charges: {min_total_charges}, Max Total Charges: {max_total_charges}") 

# Hàm công thức vectorize để chuẩn hóa dữ liệu
def normalize(min, max, column):
    return (column - min) / (max - min) 

normalized_tenure = normalize(min_tenure, max_tenure, tenure_column)
normalized_monthly_charges = normalize(min_monthly_charges, max_monthly_charges, monthly_charges_column)
normalized_total_charges = normalize(min_total_charges, max_total_charges, total_charges_column)

print(f"Normalized Tenure:\n{normalized_tenure}")
print(f"Normalized Monthly Charges:\n{normalized_monthly_charges}")
print(f"Normalized Total Charges:\n{normalized_total_charges}")

Min Tenure: 0, Max Tenure: 72
Min Monthly Charges: 18.25, Max Monthly Charges: 118.75
Min Total Charges: 18.8, Max Total Charges: 8684.8
Normalized Tenure:
[0.013888888888888888 0.4722222222222222 0.027777777777777776 ...
 0.1527777777777778 0.05555555555555555 0.9166666666666666]
Normalized Monthly Charges:
[0.11542288557213931 0.3850746268656717 0.35422885572139307 ...
 0.1129353233830846 0.5587064676616916 0.8696517412935324]
Normalized Total Charges:
[0.0012751  0.21586661 0.01031041 ... 0.03780868 0.03321025 0.78764136]


In [68]:
# Đưa kết quả vào trong mảng
array_normalized = np.array([normalized_tenure, normalized_monthly_charges, normalized_total_charges]).T 

print(f"Normalized Array:\n{array_normalized}")

Normalized Array:
[[0.013888888888888888 0.11542288557213931 0.001275098084468036]
 [0.4722222222222222 0.3850746268656717 0.21586660512347103]
 [0.027777777777777776 0.35422885572139307 0.010310408492960998]
 ...
 [0.1527777777777778 0.1129353233830846 0.037808677590583886]
 [0.05555555555555555 0.5587064676616916 0.03321024694207247]
 [0.9166666666666666 0.8696517412935324 0.7876413570274636]]


Q4. Use boolean indexing to filter customers with tenure > 12 and MonthlyCharges greater than the dataset average.

In [69]:
mask = (array[:, 0] > 12) & (array[:, 1] > df.MonthlyCharges.mean())

print(f"Mask:\n{mask}")

Mask:
[False False False ... False False  True]


Q5. Compute the correlation matrix between numerical features using NumPy (without using Pandas).

In [70]:
# Lọc các dòng sạch trong cột total charges để tính toán ma trận tương quan
clean_total_charges_column = ~np.isnan(total_charges_column)

# Clean lại array để thực hiện tính toán
array_clean = array[clean_total_charges_column]
array_clean = array_clean.astype(float)
print(f"Cleaned Array:\n{array_clean}")

Cleaned Array:
[[1.0000e+00 2.9850e+01 2.9850e+01]
 [3.4000e+01 5.6950e+01 1.8895e+03]
 [2.0000e+00 5.3850e+01 1.0815e+02]
 ...
 [1.1000e+01 2.9600e+01 3.4645e+02]
 [4.0000e+00 7.4400e+01 3.0660e+02]
 [6.6000e+01 1.0565e+02 6.8445e+03]]


In [71]:
correlation_matrix = np.corrcoef(array_clean, rowvar=False)
print(f"Correlation Matrix:\n{correlation_matrix}")

Correlation Matrix:
[[1.         0.24686177 0.82588046]
 [0.24686177 1.         0.6510648 ]
 [0.82588046 0.6510648  1.        ]]


Vectorization & Linear Algebra

Q6. Implement a fully vectorized function to compute pairwise Euclidean distance between customers using numerical features only (avoid explicit Python loops).

In [72]:
def pairwise_euclidean(matrix):
    sq_norms = np.sum(matrix**2, axis=1, keepdims=True)
    inside_sqrt = sq_norms + sq_norms.T - 2 * np.dot(matrix, matrix.T)
    # Đảm bảo không có giá trị âm
    inside_sqrt = np.clip(inside_sqrt, a_min=0, a_max=None)
    dist_matrix = np.sqrt(inside_sqrt)
    return dist_matrix

In [73]:
print(f"Pairwise Euclidean Distance Matrix:\n{pairwise_euclidean(array_clean)}")

Pairwise Euclidean Distance Matrix:
[[   0.         1860.14019163   81.90170938 ...  316.75798727
   280.32885153 6815.38151995]
 [1860.14019163    0.         1781.64009623 ... 1543.46374269
  1583.28042762 4955.34264103]
 [  81.90170938 1781.64009623    0.         ...  239.69971318
   199.52118935 6736.85316468]
 ...
 [ 316.75798727 1543.46374269  239.69971318 ...    0.
    60.36607077 6498.7277528 ]
 [ 280.32885153 1583.28042762  199.52118935 ...   60.36607077
     0.         6538.26865252]
 [6815.38151995 4955.34264103 6736.85316468 ... 6498.7277528
  6538.26865252    0.        ]]


Q7. Implement both Min-Max scaling and Z-score normalization from scratch using NumPy and compare their results.

In [74]:
def z_score_normalize(matrix):
    return (matrix - np.mean(matrix, axis=0)) / np.std(matrix, axis=0)

In [75]:
print (f"Z-score Normalized Array:\n{z_score_normalize(array_clean)}")

Z-score Normalized Array:
[[-1.28024804 -1.16169394 -0.99419409]
 [ 0.06430269 -0.26087792 -0.17373982]
 [-1.23950408 -0.36392329 -0.95964911]
 ...
 [-0.87280842 -1.17000405 -0.85451414]
 [-1.15801615  0.31916782 -0.87209546]
 [ 1.36810945  1.35793167  2.01234407]]


In [76]:
def cosine_similarity(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [77]:
sim = cosine_similarity(array_clean[0], array_clean[1])
print(f"Cosine Similarity between first two customers: {sim}")

Cosine Similarity between first two customers: 0.7281924923197327


Q9. Perform PCA manually using NumPy: construct the covariance matrix from numerical features, compute eigenvalues and eigenvectors, and project the data onto the top 2 principal components.

In [78]:
def PCA(matrix, components=2):
    # Chuẩn hóa dữ liệu
    matrix_normalized = z_score_normalize(matrix)
    
    # Tính ma trận hiệp phương sai
    covariance_matrix = np.cov(matrix_normalized, rowvar=False)
    
    # Tính giá trị riêng và vector riêng
    eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
    
    # Sắp xếp giá trị riêng và vector riêng theo thứ tự giảm dần
    sorted_indices = np.argsort(eigenvalues)[::-1]
    sorted_eigenvalues = eigenvalues[sorted_indices]
    sorted_eigenvectors = eigenvectors[:, sorted_indices]
    
    # Chọn num_components vector riêng hàng đầu
    selected_eigenvectors = sorted_eigenvectors[:, :components]
    
    # Chiếu dữ liệu lên không gian mới
    transformed_data = np.dot(matrix_normalized, selected_eigenvectors)
    
    return transformed_data

In [79]:
print(f"PCA: \n{PCA(array_clean)}")

PCA: 
[[ 1.95165689 -0.08275258]
 [ 0.20579255 -0.23514165]
 [ 1.51808264  0.52254219]
 ...
 [ 1.63168822 -0.34516629]
 [ 1.08184347  1.00900265]
 [-2.77397648  0.12278947]]


Q10. Implement batch processing by splitting the NumPy array into equal-sized batches and computing the mean vector for each batch.

In [80]:
# Kích thước batch
batch_size = 700
batches = np.array_split(array_clean, len(array) // batch_size)

print(f"Number of batches: {len(batches)}")
print(f"Shape of first batch: {batches[0].shape}") 
print(f"First batch:\n{batches[0]}")

Number of batches: 10
Shape of first batch: (704, 3)
First batch:
[[1.0000e+00 2.9850e+01 2.9850e+01]
 [3.4000e+01 5.6950e+01 1.8895e+03]
 [2.0000e+00 5.3850e+01 1.0815e+02]
 ...
 [2.9000e+01 8.4900e+01 2.5162e+03]
 [2.0000e+00 2.0550e+01 3.3600e+01]
 [4.0000e+00 4.9250e+01 2.0845e+02]]


In [81]:
mean_batch = np.mean(batches[0], axis=0)
print(f"Mean of the first batch:\n{mean_batch}")

Mean of the first batch:
[  32.05965909   66.39921875 2315.23877841]
